version: "3"
services:
  back:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    container_name: back
    environment:
      is_docker: true
  front:
    build: ./frontend
    container_name: front
#    expose:
#      - 3000
    ports:
      - "3000:3000"
#    stdin_open: true
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=wellsfargo22
      - POSTGRES_USER=postgres
      - POSTGRES_DB=to_do_app_tasks
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    container_name: db
    volumes:
      - "./database_folder:/var/lib/postgresql/data"
