version: "3"
services:
  back:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    container_name: back
    environment:
      is_docker: true
  front:
    build: ./frontend
    ports:
      - "80:80"
    container_name: front
  db:
    image: postgres # build
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_PASSWORD: 12345,
    volumes:
      - "c:/Users/user1/postgres_db:/var/lib/postgresql/data"
